In [58]:
#Step-1: We have to import the dataset to the colab notebook.
import pandas as pd #pd is a nickname of pandas.
df=pd.read_csv('Data.csv') #df is a variable,read_csv is a predefined function from pandas package.

In [59]:
type(df)

pandas.core.frame.DataFrame

In [60]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [61]:
#Step-2:Growing the input colummns and output columns
X=df.iloc[:,:-1] #input slicing

In [62]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [63]:
Y=df.iloc[:,-1]#slicing the output column

In [64]:
Y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [65]:
X=X.values

In [66]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [67]:
Y=Y.values

In [68]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [69]:
#Step3: Handling missing data and NaN values
#scenario-1:Missing values in numerical values.
#scenario-2:Missing values in nin numerical columns.
#scenario-3:Missing values in huge data set.

import numpy as np
from sklearn.impute import SimpleImputer

imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

In [70]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [71]:
#Step-4:Handling in categorial data
#which converts the text data into numeric data.
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

#Alexa-0,0,1

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough') #encoder is a method which converts text into numeric
X=ct.fit_transform(X)

In [72]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [73]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [74]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [75]:
#step-5: split the data into training and testing data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,)

In [76]:
X_train

array([[1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778]], dtype=object)

In [77]:
X_test

array([[0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0]], dtype=object)

In [78]:
Y_train

array([1, 0, 0, 0, 1, 0, 0, 1])

In [79]:
Y_test

array([1, 1])

In [80]:
#Step-6:feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])

In [81]:
X_train

array([[1.0, 0.0, 0.0, -0.37593490448012845, 0.3316732605710085],
       [0.0, 1.0, 0.0, 1.9543635762708673, 2.0148785300767416],
       [1.0, 0.0, 0.0, 0.8788412005396384, 0.85767490729155],
       [0.0, 1.0, 0.0, -1.6307110094998953, -1.0359310209023995],
       [1.0, 0.0, 0.0, -0.7344423630572047, -0.6151297035259663],
       [0.0, 0.0, 1.0, -0.05726160796717162, -1.2463316795906163],
       [0.0, 0.0, 1.0, -0.1966811751915903, -0.2995287154936414],
       [0.0, 1.0, 0.0, 0.16182628338548596, -0.007305578426673508]],
      dtype=object)

In [82]:
X_test

array([[0.0, 0.0, 1.0, -2.1684721973655097, -1.6671329969670494],
       [1.0, 0.0, 0.0, 1.5958561176937909, 1.5940772127003082]],
      dtype=object)

In [ ]:
#machine learning
#1.supervised learning-when we have labled data,and the model tasks are classification or prediction
#2.unsupervised learning-unlabeled data,model remembers the patterns,we can perfrom predictions also
#3.reinforcement learning-trail and errror method,model learns from failures.

In [85]:
#logistic regression algorithm=
#linear regression algorithm

#step-7: applying algorithm to the training data for mode
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,Y_train)

LogisticRegression(random_state=0)

In [86]:
Y_pred=classifier.predict(X_test)

In [87]:
Y_pred

array([0, 0])